GET http://localhost:3076/department
# GET http://localhost:3076/department/2

# POST http://localhost:3076/department
# Content-Type: application/json

# {
#     "ma_khoa": "15KGD",
#     "name": "Khoa Giáo dục"
# }

# PUT http://localhost:3076/department/3
# Content-Type: application/json

# {
#     "ma_khoa": "15KEDIT",
#     "name": "Khoa Edit 3"
# }

# DELETE http://localhost:3076/department/3